mixmaxhq/mongo-cursor-pagination

README.md

The library uses `_id` as a secondary sort field internally when `paginatedField` is passed.

Update README with note on index for sorting

---

README.md

Since the examples were already using async/await and arrow functions, may as well use let and const instead of var to be consistent with syntax. Also corrects minor formatting issues.

Update README with ES6 syntax

---

package.json
spec/findSpec.js
src/find.js

When passing a paginated field that has a dot notation e.g. `start.date`, the first set of results returns fine, but when using `next` or `previous`, the results are not returned correctly. This is a fix for that issue.

Fix bug where calling `find` with a `next` does not work when paginated field has dot notation

---

README.md
package.json
spec/findSpec.js
spec/findWithReqSpec.js
spec/searchSpec.js
spec/support/db.js
src/find.js
src/findWithReq.js
src/search.js

This PRs makes the package work with the native MongoDB Node.js driver, as well as with mongoist.
The tests pass but I’ve not added any new to test with the native driver. Hope that’s OK?

Support for native MongoDB driver

---

spec/findSpec.js
src/find.js

This PR adds two new params `before` and `after`.
These are used just as `next` and `previous`, with the difference that they take a document `_id` instead of a hashed version of `_id` + `paginationFieldValue`, like `next` and `previous` do.
This allows for pagination by _id even when the pagination field is not the _id. It comes at the price of an extra DB lookup, but allows for a shorter page cursor.
I’ll be updating the docs and unit tests but I first wanted to check your stance to merging this feature.
Thoughts?
NOTE: This PR was branched from my other PR so that change is also included in the diff (at the bottom of the file). I'll get the other PR ready to be merged before this one, to remedy that.

[Feature] Paginate by _id

---

src/findWithReq.js

We don't currently copy the passed `params`, which is a bit of an anti-pattern. We should copy them so we don't induce unexpected side effects.

Copy params

---

package-lock.json
package.json

Addresses vulnerability https://nodesecurity.io/advisories/660, and issue#32.

updated base64-url to 2.2.0 to address vulnerability

---

spec/aggregateSpec.js
src/aggregate.js
src/find.js
src/findWithReq.js
src/index.js
src/utils/getPropertyViaDotNotation.js
src/utils/query.js
src/utils/sanitizeParams.js
src/utils/sanitizeQuery.js

This PR introduces support for `aggregate`, it has some limitations on what can be done though so that pagination works as expected, but it covers a very common scenario: expanding subdocuments stored in separate collections, for example:
```
[
{ $match: { foo: 'bar' } },
{ $unwind: '$items' },
{ $lookup: { from: 'foo', as: 'itemDocs' }, // omiting properties for this example
{ $unwind: '$itemDocs },
{ $group: { _id: '$_id', items: { $push: '$itemDocs' } } }
]
```
Additionally I refactored a lot of the code in `find` and separated in granular functions making the code easier to understand and also makes it possible to share code between `aggregate` and `find`, also factored express request sanitization code to a standalone function so that this sanitization is available for client code.

Aggregate support

---

CHANGELOG.md
README.md
package-lock.json
package.json
spec/aggregateSpec.js
spec/findSpec.js
src/aggregate.js
src/find.js

This allows sorting 'a' < 'B' < 'c' < 'D' instead of 'B' < 'D' < 'a' < 'c', or '2' < '9' < '10' instead of '10' < '2' < '9'  by configuring a collation to use for sorting (see https://docs.mongodb.com/manual/reference/collation/ ).

feat: support locale-based collations when sorting (MX-7704)

---

package-lock.json
package.json

mongodb-extended-json version 1.7.1 had a malicious package in its dependency tree. The creator has bumped to the most recent version of event-stream to circumvent; need to bump here too.
https://www.npmjs.com/advisories/737

chore(deps): mitigate flatmap-stream malware

---

package-lock.json
package.json
spec/utils/bsonUrlEncodingSpec.js
src/utils/bsonUrlEncoding.js

Issue - https://github.com/mixmaxhq/mongo-cursor-pagination/issues/50
1. Replaces `mongodb-extended-json": "^1.7.1"` with [bson](https://www.npmjs.com/package/bson#EJSON) "bson": "^4.0.4"
2. Fixes failing test
Should be a major release, since one of the test was updated

Replace mongodb-extended-json with bson

---

package.json

The following commits fail commitlint:
```
5ed5489 Replace mongodb-extended-json with bson; Fix test
e2ab709 Exclude /dist from sublime project file.
187f1fe docs: document the interaction between collation settings and
index usage
0dcc73f Lose await in sample code of README
```
After verifying that they don't involve functional changes, we can skip
them to trigger a release when this PR is merged.
the biggest risk is that one of these commits contains a breaking change and we have to publish a new version of the module.
ensure unit tests pass.

chore(ci): skip failing commits

---

package-lock.json
package.json
test/find.test.js
test/utils/bsonUrlEncoding.test.js

Fixes https://github.com/mixmaxhq/mongo-cursor-pagination/issues/196
Fixes regression in #134 whereby in moving
from mongodb-extended-json to bson for encoding cursors, we accidentally broke support for string
_ids. This is because EJSON.stringify didn't support encoding strings. Support was added for it
in mongodb/js-bson#376 in v4.1.0.
Low. This change is also backwards-compatible, even in the case that someone stored cursors generated by a previous version of this library, because it does not change how those are decoded.
I'm relying on the unit tests to ensure this doesn't regress functionality.

fix(bson): fixes regression where string _ids were no longer supported

---

README.md
src/mongoose.plugin.js
test/mongoosePlugin.test.js

Adds support for search when using with the mongoose plugin. 
Although the manual test worked:
Could not get the jest tests to run (in general). Having problems with the specified versions and MongoDB In-Memory Server on Pop-OS. If someone could run them prior to merging, that would be great.
Tested it manually. 
Backwards compatible - no breaking changes for paginate fn name.

feat(mongoose-plugin): add search function

---

package.json

Jenkins wasn't reporting CI status in PR https://github.com/mixmaxhq/mongo-cursor-pagination/pull/289 and rather than debug the issue, I used my admin permissions to override it :(. This wasn't good because Jenkins was actually failing the build due to a bad commit message.
Low. This just skips a commit with an improper (unsemantic) commit message. Merging this should build a release of mongo-cursor pagination.
Low. No code change.
None.

fix: skip bad commit message

---

src/find.js
test/find.test.js

When `paginatedField` is not present, we were not returning
the _id field, even when it was specified to be returned.
resolves #309
* return `_id` when paginatedField is not set

fix: return _id when paginatedField is not set

---

README.md
src/aggregate.js
src/find.js
test/aggregate.test.js
test/find.test.js

Enable the use of a custom collation for a single `find` or `aggregate` call.
Why: Using the default `config.COLLATION` means we must re-index the collections to ensure our indexes match the collation. Conversely, we could use the static configuration for a single call but it opens a breach for race-condition issues:
```js
paging.config.COLLATION = { locale: 'en' };
const results = await paging.find(collection, { ... })
// if any other `.find` or `.aggregate` methods were called before the `delete` line below,
// they will use the collation set above, which may not be desired;
delete paging.config.COLLATION;
```
With the PRs code, we can use:
```js
const results = await paging.find(collection, { ..., collation: { locale: 'en' } })
```
- None. Adds capabilities.

feat: allow collation as arg on find and aggregate

---

package.json

The latest PR (https://github.com/mixmaxhq/mongo-cursor-pagination/pull/320), was merged with the "merge" strategy. This caused the commit https://github.com/mixmaxhq/mongo-cursor-pagination/commit/7a05f30859f03b1381957ce25358ecc4b9ce362d inside the PR to be added on Master, and that caused the CI to fail:
In this PR, I'm adding the failing commit to the skip list, according to the guideline: https://github.com/mixmaxhq/semantic-commitlint#skip-commits
This repo already has the `ci:commitlint` [script](https://github.com/mixmaxhq/mongo-cursor-pagination/blob/b6d34a9658a9840324e76c7113b5fa54655967e8/package.json#L15) but it is always called with the "squash and merge" approach.
To prevent the issue from happening again, I'm disabling the "merge" strategy, and leaving only the "squash and …

fix: skip commit with wrong scope

---

src/aggregate.js
src/find.js
src/utils/query.js
src/utils/sanitizeParams.js
test/aggregate.test.js
test/find.test.js

Jira: [COMM-78](https://mixmaxhq.atlassian.net/browse/COMM-78)
* Add the sort & limit stages at the end of the aggregation pipeline, instead of at the first `$match`. The previous behaviour meant, in many cases, breaking the pagination: any `$match`, `$unwind`, `$group`, etc. could change the number of items and end up returning pages with a number different from `limit`. I've checked the 4 uses of this method throughout our codebase and they are all [potentially] erroneous. In view of this, I've decided to move on, marking this as a breaking change.
* Add a `sortCaseInsensitive` option to the `aggregate` method, which will result in the results being sorted (and paginated) in case-insensitive alphabetical order.
* Use the `aggregate` method to implement the `sortCaseInsensitive` option …

feat: add a `sortCaseInsensitive` option to `find` and `aggregate`

---

README.md
package.json
src/aggregate.js

Release broke because this repo does "squash and merge", and in doing so it uses the PR title as the title for the merge commit, and it was too long for semantic commits: https://jenkins.mixmax.com/blue/organizations/jenkins/mixmaxhq%2Fmongo-cursor-pagination/detail/master/37/pipeline/
Skipping that commit -- and, while at it, pushing a couple of doc improvements.

COMM-78 skip overly long commit

---

README.md
package-lock.json
package.json
src/aggregate.js
src/find.js
src/utils/bsonUrlEncoding.js
src/utils/query.js
test/aggregate.test.js
test/find.test.js

* Ensured that if the `paginatedField`'s value is `null` or `undefined`, it gets properly transferred via the paging handles `next` and `previous`.
* If sorting case-insensitively, replace those with the empty string for comparing, as mongodb's `$toLower` transforms both `null` and `undefined` into it.
* If sorting case-sensitively, handle each of the cases, taking into account that `undefined` sorts before `null` and `null` before everything else.
* Change the README to instruct users to avoid mixing types (before it was avoiding emtpy values).
* Updated `bson` and `mongoist` even though it was not necessary for this ticket.
It is unclear whether the conditions used to check for `undefined` and `null` (or non-undefined, non-null, and combinations) will use indices efficiently. But this …

fix: properly page through undefs and nulls

---

index.js
package.json

* Change the version in `index.js` so the transpiled version is used in node versions ealier than 14.0.0, which is the first supporting optional chaining (`?.`).
None perceived: even if the transpiled version is run in a version supporting optional chaining, it should still work.
Try using this package under node 12.

fix: use the transpiled version in node 12
